config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolio_items do
    put :sort, on: :collection
  end
  resources :blogs do 
  	member do
  		get :toggle_status
  	end	
  end	
  get 'about-me',  to: 'pages#about'  
  get 'contact',   to: 'pages#contact'  
  get 'tech-news', to: 'pages#tech_news'  
  
  # create web socket connection
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot app-footer">
  <div class="inner">
    <p><%= copyright_helper %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Milan Cancarevic</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_helper %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Milan's blog</h1>
    <%= link_to 'New Blog Post', new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Welcome to my blog, enjoy reading awesome Ruby on Rails articles</p>
  </div>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "instagram" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", portfolio_items_path %> / 
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copyright_helper %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Portfolio</h1>
    <p class="lead text-muted">In this portfolio I've listed some of my favorite projects that I've built through the years. These application capture a wide range of the applications that love to develop, including: web and mobile applications, enterprise projects, machine learning projects, and tools used by millions of users each day.</p>
    <p>
      <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Projekat za IT370</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <%= link_to "Milan Cancarevic", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>