config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolio_items do
    put :sort, on: :collection
  end
  resources :blogs do 
  	member do
  		get :toggle_status
  	end	
  end	
  get 'about-me',  to: 'pages#about'  
  get 'contact',   to: 'pages#contact'  
  get 'tech-news', to: 'pages#tech_news'  
  
  # create web socket connection
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/portfolio_item.rb
class PortfolioItem < ApplicationRecord

	# upload
	mount_uploader :thumb_image, PortfolioUploader
	mount_uploader :main_image, PortfolioUploader

  # relations
	has_many :technologies

  # nested attributes (must be placed below relations)
  accepts_nested_attributes_for :technologies, 
  															allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

	# validations
	validates_presence_of :title, :body

	# class methods
	def self.by_position
		order("position ASC")
	end
end

app/controllers/portfolio_items_controller.rb
class PortfolioItemsController < ApplicationController
	before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
	layout 'portfolio'
  access all: [:show, :index], user: {except: [:destroy, :create, :new, :update, :edit, :sort]}, site_admin: :all


	def index
		@portfolio_items = PortfolioItem.by_position
	end

	def sort
		params[:order].each do |k,v|
			PortfolioItem.find(v[:id]).update(position: v[:position])
		end

		render nothing: true
	end

	def new
		@portfolio_item = PortfolioItem.new
	end

	def create
		@portfolio_item = PortfolioItem.new(portfolio_item_params)

		respond_to do |format|
			if @portfolio_item.save
				format.html { redirect_to portfolio_items_path, notice: 'Item is live' }
			else
				format.html { render :new }
			end
		end
	end

	def edit
	end

	def update
  	respond_to do |format|
      if @portfolio_item.update(portfolio_item_params)
        format.html { redirect_to portfolio_items_path, notice: 'Item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
	end

	def show
	end

	def destroy
		@portfolio_item.destroy
		respond_to do |format|
			format.html { redirect_to portfolio_items_url, notice: "destroyed item" }
		end		
	end


	private

	def portfolio_item_params
		params.require(:portfolio_item).permit(:title, 
																					 :subtitle, 
																					 :thumb_image, 
																					 :main_image, 
																					 :body, 
																					 technologies_attributes: [:id, :name, :_destroy])
	end

	def set_portfolio_item
		@portfolio_item = PortfolioItem.find(params[:id])
	end

end

app/helpers/portfolio_items_helper.rb
module PortfolioItemsHelper
	def image_generator width, height
		"http://placehold.it/#{width}x#{height}"
	end

	def portfolio_img_helper img, type
		if img.model.thumb_image? || img.model.main_image?
			img
		elsif type == 'thumb'
			image_generator(350,200)
		else
			image_generator(400,600)	
		end	
	end
end

app/views/portfolio_items/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator_helper error %>    
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= f.file_field :main_image, style: 'display:none;' %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file <%= f.file_field :thumb_image, style: 'display:none;' %>
        </label>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h2>Technolgies Used:</h2>
    <div>
      <%= f.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>

      <div>
        <%= link_to_add_association 'Add technology', f, :technologies %>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolio_items/_portfolio_item.html.erb
<div class="card" data-id="<%= portfolio_item.id %>">
  <%= image_tag portfolio_img_helper(portfolio_item.thumb_image, 'thumb') %>
  <p class="card-text">
    <span><%= link_to portfolio_item.title, portfolio_item_path(portfolio_item) %></span> <%= portfolio_item.subtitle %>
  </p>
</div>

app/views/portfolio_items/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove technology', f %>
</div>

app/views/portfolio_items/edit.html.erb
<div class="container portfolio-container">
	<h1>Edit item</h1>

	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolio_items/index.html.erb
<div class="album text-muted">
  <div class="container">
  	<div class="row <%= 'sortable' if logged_in?(:site_admin) %> ">
	    <%= render @portfolio_items %>
	  </div>
  </div>
</div>

app/views/portfolio_items/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>  
</div>

app/views/portfolio_items/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img_helper(@portfolio_item.main_image, 'main') %>
    </div>

    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>

      <hr>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%= @portfolio_item.body %></p>

      <hr>

      <h3>Technologies Used:</h3>

      <% @portfolio_item.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>

      <% if logged_in?(:site_admin) %>
        <%= link_to "Edit item", edit_portfolio_item_path(@portfolio_item), class: 'btn btn-warning' %>
      <% end %>
    </div>
  </div>
</div>